settings:
  title: 'REI站点状态监测'
  url: 'https://status.rei1.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: ' √ 所有站点工作正常'
  notAllmonitorsOperational: ' ※ 部分网站异常'
  monitorLabelOperational: '运行中'
  monitorLabelNotOperational: '已停止/失联'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 次波动' # 

monitors:
  - id: Wblog # unique identifier
    name: WBLOG
    description: '札记万物' # default=empty
    url: 'https://wblog.rei1.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true



  - id: VPS-ly65
    name: ly65的VPS
    description: '主vps'
    url: 'https://vps1.ly65.top/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: sf-ly65
    name: 静态文件
    description: '静态文件'
    url: 'https://sf-cip.ly65.top/gen_200'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: JimaLink
    name: JimaLink
    description: 'Jima的个人主页'
    url: 'https://jimmma.top/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: JimaNav
    name: JimaNav
    description: 'Jima的导航页'
    url: 'https://nav.jimmma.top/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true


  - id: Alist
    name: 云上NAS
    description: 'Alist'
    url: 'https://alist.rei1.top/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true


  - id: IPTV
    name: IPTV源服务
    description: 'IPTV源服务（注意此站点检测使用为分离工作模式）'
    url: 'http://status.nv6tv.improve-rei1.eu.org/ycl_iptv.m3u'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true







