settings:
  title: 'REI站点状态监测'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: ' √ 所有站点工作正常'
  notAllmonitorsOperational: ' ！ 部分网站异常'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Wblog # unique identifier
    name: wblog.rei1.top
    description: '札记万物' # default=empty
    url: 'https://wblog.rei1.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: JimaLink
    name: jimmma.top
    description: 'Jima的个人主页'
    url: 'https://jimmma.top'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true


