settings:
  title: 'REI站点状态监测'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 10 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: ' √ 所有站点工作正常'
  notAllmonitorsOperational: ' ！ 部分网站异常'
  monitorLabelOperational: '运行中'
  monitorLabelNotOperational: '已停止/失联'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Wblog # unique identifier
    name: wblog.rei1.top
    description: '札记万物' # default=empty
    url: 'https://wblog.rei1.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: JimaLink
    name: jimmma.top
    description: 'Jima的个人主页'
    url: 'https://jimmma.top'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: JimaNav
    name: nav.jimmma.top
    description: 'Jima的导航页'
    url: 'https://nav.jimmma.top'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: 机密驿站
    name: sd.rei1.top
    description: '机密驿站'
    url: 'https://sd.rei1.top'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: IPTV
    name: nv6tv.rei1.top
    description: 'IPTV源服务'
    url: 'http://4.216.147.218:3000/fmml_ipv6.m3u'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: IPTV(备用)
    name: v6tv.rei1.top
    description: 'IPTV源服务(备用)'
    url: 'http://8.130.99.175:3000/fmml_ipv6.m3u'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: TVEPG
    name: tvepg.rei1.top
    description: 'EPG服务'
    url: 'http://4.216.147.218:3000/epg/51zmt.xml'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true




